-- GCP v4: exactly one public table; dataset provisioned separately. State stays in GCS.

CREATE TABLE IF NOT EXISTS `${BQ_PROJECT}.${BQ_DATASET}.${BQ_TABLE}` (
  `ordem_etapa` INT64 NOT NULL,
  `projeto_nome` STRING NOT NULL,
  `status_nome` STRING NOT NULL,
  `entrada_status_local` DATETIME,
  `saida_status_local` DATETIME,
  `duracao_horas` FLOAT64,
  `marca_nome` STRING,
  `talento_nome` STRING,
  `responsavel_orcamento` STRING,
  `eh_retorno` BOOL NOT NULL,
  `item_id` INT64 NOT NULL,
  `board_id` INT64 NOT NULL,
  `interval_id` STRING NOT NULL,
  `qualidade_historico` STRING NOT NULL,
  `intervalo_aberto` BOOL NOT NULL,
  `status_final` BOOL NOT NULL,
  `corte_local` DATETIME NOT NULL,
  `elegivel_comparacao` BOOL NOT NULL,
  `horas_observadas_encerradas` FLOAT64,
  `status_atual_nome` STRING NOT NULL,
  `projeto_na_fila` BOOL NOT NULL,
  `tempo_desde_entrada_horas` FLOAT64,
  `tempo_status_atual_horas` FLOAT64,
  `responsavel_situacao` STRING NOT NULL,
  `cadastro_referencia_utc` TIMESTAMP,
  `versao_regras` STRING NOT NULL,
  `item_sk` STRING NOT NULL,
  `board_sk` STRING NOT NULL,
  `status_id` STRING NOT NULL,
  `status_sk` STRING NOT NULL,
  `entrada_status_utc` TIMESTAMP,
  `saida_status_utc` TIMESTAMP,
  `corte_utc` TIMESTAMP NOT NULL,
  `duracao_horas_uteis` FLOAT64,
  `horas_uteis_observadas_encerradas` FLOAT64,
  `tempo_status_atual_horas_uteis` FLOAT64,
  `tempo_desde_entrada_horas_uteis` FLOAT64,
  `expediente` STRING NOT NULL,
  `versao_calendario` STRING NOT NULL
)
CLUSTER BY board_id, item_id, status_id;
