-- Candidato: NAO executar antes da migracao transacional.
CREATE TABLE `gglobo-viu-dados-hdg-prd.viu_agenciamento.monday_ciclos_orcamento` (
  `projeto_id` STRING NOT NULL,
  `ciclo_id` STRING NOT NULL,
  `numero_ciclo` INT64 NOT NULL,
  `tipo_ciclo` STRING NOT NULL,
  `interval_id_inicio` STRING NOT NULL,
  `interval_id_fim` STRING,
  `item_id_viu2` INT64,
  `item_id_globocorp` INT64,
  `inicio_utc` TIMESTAMP NOT NULL,
  `fim_utc` TIMESTAMP,
  `corte_utc` TIMESTAMP NOT NULL,
  `situacao` STRING NOT NULL,
  `operacao_horas_corridas` FLOAT64,
  `operacao_horas_uteis` FLOAT64,
  `terceiros_horas_corridas` FLOAT64,
  `terceiros_horas_uteis` FLOAT64,
  `standby_horas_corridas` FLOAT64,
  `standby_horas_uteis` FLOAT64,
  `duracao_completa` BOOL NOT NULL,
  `kpi_entrega_observada` BOOL NOT NULL,
  `contem_estimativa` BOOL NOT NULL,
  `contem_idade_aberta` BOOL NOT NULL,
  `quantidade_passagens_operacionais` INT64 NOT NULL,
  `motivos_json` STRING NOT NULL,
  `versao_regra` STRING NOT NULL,
  `versao_calendario` STRING NOT NULL
) CLUSTER BY projeto_id, situacao;
