-- Reference only: initial load uses an explicit schema and WRITE_EMPTY.
CREATE TABLE `gglobo-viu-dados-hdg-prd.viu_agenciamento.monday_sla_orcamento` (
  `ordem_etapa` INT64,
  `projeto_nome` STRING,
  `status_nome` STRING,
  `entrada_status_local` DATETIME,
  `saida_status_local` DATETIME,
  `duracao_horas` FLOAT64,
  `duracao_horas_uteis` FLOAT64,
  `marca_nome` STRING,
  `talento_nome` STRING,
  `responsavel_orcamento` STRING,
  `marca_original` STRING,
  `talento_original` STRING,
  `eh_retorno` BOOL,
  `retorno_observado_origem` BOOL NOT NULL,
  `projeto_id` STRING NOT NULL,
  `item_id` INT64 NOT NULL,
  `board_id` INT64 NOT NULL,
  `ambiente_origem` STRING NOT NULL,
  `conta_origem` STRING NOT NULL,
  `interval_id` STRING NOT NULL,
  `interval_id_origem` STRING NOT NULL,
  `item_id_viu2` INT64 NOT NULL,
  `item_id_globocorp` INT64 NOT NULL,
  `ordem_origem` INT64 NOT NULL,
  `status_index` STRING NOT NULL,
  `tipo_registro` STRING NOT NULL,
  `qualidade_historico_origem` STRING NOT NULL,
  `qualidade_identidade` STRING NOT NULL,
  `continuidade_validada` BOOL NOT NULL,
  `elegivel_comparacao` BOOL NOT NULL,
  `validacao_negocio` STRING NOT NULL,
  `entrada_status_utc` TIMESTAMP,
  `saida_status_utc` TIMESTAMP,
  `corte_globocorp_utc` TIMESTAMP NOT NULL,
  `cadastro_referencia_utc` TIMESTAMP,
  `versao_contrato` STRING NOT NULL,
  `versao_calendario_origem` STRING NOT NULL,
  `pendencias_json` STRING NOT NULL,
  `registro_origem_json` STRING NOT NULL,
  `status_terminal` BOOL,
  `finalizacao_observada_utc` TIMESTAMP,
  `situacao_sla_registro` STRING NOT NULL,
  `ciclo_observado_origem` INT64 NOT NULL,
  `reabertura_comprovada_origem` BOOL NOT NULL,
  `tempo_ciclo_observado_horas` FLOAT64,
  `sla_etapa_horas_uteis` FLOAT64,
  `classificacao_consumo` STRING NOT NULL,
  `motivos_inelegibilidade_kpi_json` STRING NOT NULL,
  `versao_regra_kpi` STRING NOT NULL,
  `quantidade_passagens_projeto` INT64 NOT NULL,
  `qualidade_trajetoria` STRING NOT NULL,
  `limitacoes_trajetoria_json` STRING NOT NULL,
  `eh_ultima_etapa_observada` BOOL NOT NULL,
  `versao_regra_trajetoria` STRING NOT NULL,
  `saida_estimada_utc` TIMESTAMP,
  `saida_estimada_local` DATETIME,
  `duracao_estimada_horas` FLOAT64,
  `duracao_estimada_horas_uteis` FLOAT64,
  `metodo_estimativa` STRING NOT NULL,
  `interval_id_referencia_estimativa` STRING,
  `versao_regra_estimativa` STRING NOT NULL,
  `versao_calendario_estimativa` STRING,
  `duracao_analise_horas` FLOAT64,
  `duracao_analise_horas_uteis` FLOAT64,
  `origem_duracao_analise` STRING NOT NULL,
  `versao_regra_duracao_analise` STRING NOT NULL,
  `versao_regra_precificacao` STRING NOT NULL,
  `papel_precificacao` STRING NOT NULL,
  `ciclo_precificacao_id` STRING,
  `situacao_ciclo_precificacao` STRING NOT NULL,
  `motivos_ciclo_precificacao_json` STRING NOT NULL,
  `entrega_precificacao_observada` BOOL NOT NULL,
  `inicio_precificacao_utc` TIMESTAMP,
  `fim_precificacao_utc` TIMESTAMP,
  `precificacao_horas_corridas` FLOAT64,
  `precificacao_horas_uteis` FLOAT64,
  `pausas_precificacao_horas_corridas` FLOAT64,
  `pausas_precificacao_horas_uteis` FLOAT64,
  `janela_precificacao_horas_corridas` FLOAT64,
  `contribuicao_precificacao_horas_corridas` FLOAT64,
  `contribuicao_precificacao_horas_uteis` FLOAT64,
  `cadastro_atual_marca` STRING,
  `cadastro_atual_talentos_exclusivos_json` STRING,
  `cadastro_atual_interveniencia` STRING,
  `cadastro_atual_orcamento_json` STRING,
  `cadastro_atual_talent_manager_json` STRING,
  `cadastro_atual_gp_json` STRING,
  `cadastro_atual_conteudo_json` STRING,
  `cadastro_atual_producao_json` STRING,
  `cadastro_atual_audiencia_json` STRING,
  `cadastro_atual_tipo_projeto` STRING,
  `cadastro_atual_tipo_input` STRING,
  `cadastro_atual_tipo_output` STRING,
  `cadastro_atual_capturado_em` TIMESTAMP,
  `cadastro_atual_origem_json` STRING
) CLUSTER BY projeto_id, ambiente_origem, item_id;
